"""Add Index

Revision ID: 2b1a70fd649d
Revises: 74d4f26f9749
Create Date: 2023-12-08 14:46:11.914687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2b1a70fd649d'
down_revision: Union[str, None] = '74d4f26f9749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_FullName'), 'users', ['FullName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_FullName'), table_name='users')
    # ### end Alembic commands ###
