"""Initial Creation

Revision ID: 74d4f26f9749
Revises: 
Create Date: 2023-12-05 00:23:45.474571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '74d4f26f9749'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('LastName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('MiddleName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FullName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Phone1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Phone2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Email1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Email2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('count', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
